#############################################################################
# Makefile for building: nifRenderer
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  nifRenderer.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile nifRenderer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wno-unknown-pragmas -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = nifRenderer1.0.0
DISTDIR = /home/s/scew5145/Downloads/nifRenderer/.tmp/nifRenderer1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -Lniflib/build/ -lniflib_static -lglut -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		nifRenderer.cpp \
		DDSLoader.cpp \
		nifQGLWidget.cpp \
		viewer.cpp moc_nifQGLWidget.cpp \
		moc_viewer.cpp
OBJECTS       = main.o \
		nifRenderer.o \
		DDSLoader.o \
		nifQGLWidget.o \
		viewer.o \
		moc_nifQGLWidget.o \
		moc_viewer.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		nifRenderer.pro nifRenderer.h \
		DDSLoader.h \
		nifQGLWidget.h \
		viewer.h \
		niflib/include/niflib.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/BSShaderTextureSet.h main.cpp \
		nifRenderer.cpp \
		DDSLoader.cpp \
		nifQGLWidget.cpp \
		viewer.cpp
QMAKE_TARGET  = nifRenderer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = nifRenderer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nifRenderer.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		nifRenderer.pro \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile nifRenderer.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
nifRenderer.pro:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile nifRenderer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents nifRenderer.h DDSLoader.h nifQGLWidget.h viewer.h niflib/include/niflib.h niflib/include/obj/NiNode.h niflib/include/obj/NiSkinInstance.h niflib/include/obj/NiTriShape.h niflib/include/obj/NiTriShapeData.h niflib/include/obj/BSLightingShaderProperty.h niflib/include/obj/BSShaderTextureSet.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp nifRenderer.cpp DDSLoader.cpp nifQGLWidget.cpp viewer.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_nifQGLWidget.cpp moc_viewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_nifQGLWidget.cpp moc_viewer.cpp
moc_nifQGLWidget.cpp: nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h \
		nifQGLWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/s/scew5145/Downloads/nifRenderer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include nifQGLWidget.h -o moc_nifQGLWidget.cpp

moc_viewer.cpp: nifQGLWidget.h \
		nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h \
		viewer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/s/scew5145/Downloads/nifRenderer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewer.h -o moc_viewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp viewer.h \
		nifQGLWidget.h \
		nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

nifRenderer.o: nifRenderer.cpp nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nifRenderer.o nifRenderer.cpp

DDSLoader.o: DDSLoader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DDSLoader.o DDSLoader.cpp

nifQGLWidget.o: nifQGLWidget.cpp nifQGLWidget.h \
		nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nifQGLWidget.o nifQGLWidget.cpp

viewer.o: viewer.cpp viewer.h \
		nifQGLWidget.h \
		nifRenderer.h \
		DDSLoader.h \
		niflib/include/niflib.h \
		niflib/include/dll_export.h \
		niflib/include/nif_math.h \
		niflib/include/nif_versions.h \
		niflib/include/Ref.h \
		niflib/include/nif_basic_types.h \
		niflib/include/gen/enums.h \
		niflib/include/obj/NiNode.h \
		niflib/include/obj/NiAVObject.h \
		niflib/include/obj/NiObjectNET.h \
		niflib/include/obj/NiObject.h \
		niflib/include/RefObject.h \
		niflib/include/Type.h \
		niflib/include/gen/BoundingBox.h \
		niflib/include/NIF_IO.h \
		niflib/include/Key.h \
		niflib/include/gen/enums_intl.h \
		niflib/include/obj/NiSkinInstance.h \
		niflib/include/obj/NiTriShape.h \
		niflib/include/obj/NiTriBasedGeom.h \
		niflib/include/gen/BodyPartList.h \
		niflib/include/obj/NiGeometry.h \
		niflib/include/gen/SkinWeight.h \
		niflib/include/obj/NiGeometryData.h \
		niflib/include/obj/NiTriShapeData.h \
		niflib/include/obj/NiTriBasedGeomData.h \
		niflib/include/gen/MatchGroup.h \
		niflib/include/obj/BSLightingShaderProperty.h \
		niflib/include/obj/NiProperty.h \
		niflib/include/obj/BSShaderTextureSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer.o viewer.cpp

moc_nifQGLWidget.o: moc_nifQGLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nifQGLWidget.o moc_nifQGLWidget.cpp

moc_viewer.o: moc_viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewer.o moc_viewer.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

